# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20190122_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='订单唯一编号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='signing_mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='signing_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='签收人'),
        ),
    ]
