# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20190122_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='trade_status',
            new_name='pay_status',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signing_mobile',
            new_name='signer_mobile',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signing_name',
            new_name='signer_name',
        ),
    ]
