# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-19 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_studentinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='desc',
            new_name='goods_desc',
        ),
    ]
